# Generated by Django 4.0.4 on 2022-06-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accesorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accesorio_name', models.CharField(max_length=200)),
                ('accesorio_tipo', models.CharField(max_length=100)),
                ('accesorio_marca', models.CharField(max_length=100)),
                ('accesorio_precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Championes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('championes_name', models.CharField(max_length=200)),
                ('championes_color', models.CharField(max_length=100)),
                ('championes_marca', models.CharField(max_length=100)),
                ('championes_precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Marcas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contacto_name', models.CharField(max_length=100)),
                ('contacto_mail', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ropa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ropa_name', models.CharField(max_length=200)),
                ('ropa_color', models.CharField(max_length=100)),
                ('ropa_marca', models.CharField(max_length=100)),
                ('ropa_precio', models.FloatField()),
            ],
        ),
    ]
