# Generated by Django 4.0.4 on 2022-06-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_rename_imagen_ropa_ropa_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesorios',
            name='accesorio_imagen',
            field=models.ImageField(null=True, upload_to='accesorios'),
        ),
        migrations.AddField(
            model_name='championes',
            name='championes_imagen',
            field=models.ImageField(null=True, upload_to='championes'),
        ),
    ]
