# Generated by Django 4.0.4 on 2022-06-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_accesorios_accesorio_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='championes',
            name='championes_imagen',
            field=models.ImageField(null=True, upload_to='ropa'),
        ),
    ]
