# Generated by Django 4.0.4 on 2022-06-18 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_alter_championes_championes_imagen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesorios',
            options={'verbose_name': 'Accesorio', 'verbose_name_plural': 'Pila de Accesorios'},
        ),
        migrations.AlterModelOptions(
            name='championes',
            options={'verbose_name': 'Champion', 'verbose_name_plural': 'Banda de Championes'},
        ),
        migrations.AlterModelOptions(
            name='marcas',
            options={'verbose_name': 'Marca', 'verbose_name_plural': 'Marcas'},
        ),
        migrations.AlterModelOptions(
            name='ropa',
            options={'verbose_name': 'Ropa', 'verbose_name_plural': 'Mucha Ropa'},
        ),
    ]
