# Generated by Django 4.0.4 on 2022-06-20 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0007_alter_accesorios_options_alter_championes_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marcas',
            old_name='name',
            new_name='marcas_name',
        ),
        migrations.RemoveField(
            model_name='ropa',
            name='ropa_marca',
        ),
        migrations.AddField(
            model_name='ropa',
            name='marcas_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.marcas'),
        ),
    ]
