# Generated by Django 4.0.4 on 2022-06-20 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0009_rename_marcas_name_ropa_ropa_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesorios',
            name='accesorio_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.marcas'),
        ),
        migrations.AlterField(
            model_name='championes',
            name='championes_marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Tienda.marcas'),
        ),
    ]
