# Generated by Django 4.0.4 on 2022-06-30 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0010_alter_accesorios_accesorio_marca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonio_name', models.CharField(max_length=200)),
                ('testimonio_profesion', models.CharField(max_length=200)),
                ('testimonio_chamuyo', models.CharField(max_length=500)),
                ('testimonio_imagen', models.ImageField(null=True, upload_to='testimonios')),
            ],
        ),
    ]
