# Generated by Django 4.0.4 on 2022-06-30 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0011_testimonios'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testimonios',
            options={'verbose_name': 'Testimonio', 'verbose_name_plural': 'Testimonios'},
        ),
    ]
