# Generated by Django 4.0.4 on 2022-07-03 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0012_alter_testimonios_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonios',
        ),
    ]
