# Generated by Django 4.0.4 on 2022-07-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0013_delete_testimonios'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_device', models.ImageField(upload_to='nosotros')),
            ],
        ),
    ]
